export const RaceTemplate = {
  no: {
    hp: 1,
    speed: 1,
    dexterity: 1,
    strength: 1,
    agility: 1,
    insight: 1,
    magic: 0,
    regenHp: 1,
    regenSpeed: 1,
    regenAgility: 1,
  },
  an: {
    hp: 1000,
    speed: 24,
    dexterity: 20,
    strength: 100,
    agility: 48,
    insight: 10,
    magic: 0,
    regenHp: 10,
    regenSpeed: 0.5,
    regenAgility: 1,
  },
  de: {
    hp: 1000,
    speed: 24,
    dexterity: 20,
    strength: 100,
    agility: 48,
    insight: 10,
    magic: 0,
    regenHp: 10,
    regenSpeed: 0.5,
    regenAgility: 1,
  },
  hu: {
    hp: 1000,
    speed: 24,
    dexterity: 20,
    strength: 100,
    agility: 48,
    insight: 10,
    magic: 0,
    regenHp: 10,
    regenSpeed: 0.5,
    regenAgility: 1,
  },
};
