import { Races } from '@models';

export const RaceTemplate = {
  no: {
    hp: 0,
    speed: 0,
    dexterity: 0,
    strength: 0,
    agility: 0,
    insight: 0,
    magic: 0,
    regenHp: 0,
    regenSpeed: 0,
    regenAgility: 0,
  },
  an: {
    hp: 0,
    speed: 0,
    dexterity: 0,
    strength: 0,
    agility: 0,
    insight: 0,
    magic: 0,
    regenHp: 0,
    regenSpeed: 0,
    regenAgility: 0,
  },
  de: {
    hp: 0,
    speed: 0,
    dexterity: 0,
    strength: 0,
    agility: 0,
    insight: 0,
    magic: 0,
    regenHp: 0,
    regenSpeed: 0,
    regenAgility: 0,
  },
  hu: {
    hp: 0,
    speed: 0,
    dexterity: 0,
    strength: 0,
    agility: 0,
    insight: 0,
    magic: 0,
    regenHp: 0,
    regenSpeed: 0,
    regenAgility: 0,
  },
};
