
export const RaceTemplate = {
  no: {
    hp: 1,
    speed: 1,
    dexterity: 1,
    strength: 1,
    agility: 1,
    insight: 1,
    magic: 0,
    regenHp: 1,
    regenSpeed: 1,
    regenAgility: 1,
  },
  an: {
    hp: 200,
    speed: 6,
    dexterity: 9,
    strength: 20,
    agility: 2,
    insight: 5,
    magic: 0,
    regenHp: 5,
    regenSpeed: 1,
    regenAgility: 1,
  },
  de: {
    hp: 200,
    speed: 6,
    dexterity: 9,
    strength: 20,
    agility: 2,
    insight: 5,
    magic: 0,
    regenHp: 5,
    regenSpeed: 1,
    regenAgility: 1,
  },
  hu: {
    hp: 200,
    speed: 6,
    dexterity: 9,
    strength: 20,
    agility: 2,
    insight: 5,
    magic: 0,
    regenHp: 5,
    regenSpeed: 1,
    regenAgility: 1,
  },
};
